import { test, expect } from '@playwright/test';
test('test', async ({ page }) => {
  await page.goto('https://parabank.parasoft.com/parabank/index.htm?ConnType=JDBC');  
  await page.locator('input[name="username"]').click();
  await page.locator('input[name="username"]').fill('user');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('test');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Bill Pay' }).click();
  await page.locator('input[name="payee\\.name"]').click();
  await page.locator('input[name="payee\\.name"]').fill('tset');
  await page.locator('input[name="payee\\.name"]').press('Tab');
  await page.locator('input[name="payee\\.address\\.street"]').fill('haha');
  await page.locator('input[name="payee\\.address\\.street"]').press('Tab');
  await page.locator('input[name="payee\\.address\\.city"]').fill('lovers streer');
  await page.locator('input[name="payee\\.address\\.city"]').press('Tab');
  await page.locator('input[name="payee\\.address\\.city"]').click();
  await page.locator('input[name="payee\\.address\\.city"]').fill('gang city');
  await page.locator('input[name="payee\\.address\\.city"]').press('Tab');
  await page.locator('input[name="payee\\.address\\.state"]').fill('state 1');
  await page.locator('input[name="payee\\.address\\.state"]').press('Tab');
  await page.locator('input[name="payee\\.address\\.zipCode"]').fill('87683');
  await page.locator('input[name="payee\\.address\\.zipCode"]').press('Tab');
  await page.locator('input[name="payee\\.phoneNumber"]').fill('987654321');
  await page.locator('input[name="payee\\.phoneNumber"]').press('Tab');
  await page.locator('input[name="payee\\.accountNumber"]').fill('1234567');
  await page.locator('input[name="payee\\.accountNumber"]').press('Tab');
  await page.locator('input[name="verifyAccount"]').fill('1234567');
  await page.getByRole('table').click();
  await page.locator('input[name="amount"]').click();
  await page.locator('input[name="amount"]').fill('12378');
  await page.getByRole('table').click();
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await page.getByRole('link', { name: 'Log Out' }).click();
});
